### PR TITLE
Added metrics related to the current print.

### PR DESCRIPTION
**Pull request by danilodorgam**
- klipper_current_print_total_duration
- klipper_current_print_layer_height
- klipper_current_print_first_layer_height
- klipper_current_print_object_height
- klipper_gcode_position_z
With the above metrics it is possible to calculate the total layers and current layer
image

### CODE REVIEW

**Comment by scross01** [comment]
Thanks for the pull request submission, looks like a useful addition.  I'll review the code this week and let you know if any changes are needed.  The first commit appears to have updated all files, maybe a carriage return/line feed character issue.

**Comment by danilodorgam** [comment]
I believe that was it, my ide adjusted everything.
I'll see how to fix

**Comment by scross01** [comment]
I was able to resolve the line endings problem.

```
git config --global core.autocrlf true
git add --renormalize .
```

https://stackoverflow.com/questions/14564946/git-status-shows-changed-files-but-git-diff-doesnt

**Comment by scross01** [comment]
Merged to `main` with some minor updates, and released with `v0.10.0`

**Pull request merged**
